title: Durell Smith
email: d7smith@ucsd.edu
logo: /assets/img/logo.jpg
description: Technology Enthusiast 
description2: Computer Science Aficionado
show_downloads: false
google_analytics:
github_username: durell
theme: jekyll-theme-minimal
