title: Durell Smith
email: d7smith@ucsd.edu
logo: /assets/img/logo.png
description: Computer Science Aficionado
show_downloads: true
google_analytics:
github_username: durell
theme: jekyll-theme-minimal
